apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  labels:
    name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webhook
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: webhook
    spec:
      containers:
        - name: webhook
          image: ghcr.io/sngular/gitops-webhook:v0.2.1
          ports:
          - containerPort: 8080
            name: http
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 10Mi
