apiVersion: v1
kind: Service
metadata:
  name: webhook
  labels:
    name: webhook
spec:
  type: ClusterIP
  selector:
    name: webhook
  ports:
    - name: http
      port: 80
      targetPort: http
